// flow-typed signature: 588fe3f50f8c1ccecd4811e3647939e0
// flow-typed version: <<STUB>>/esformatter-quote-props_v^2.0.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'esformatter-quote-props'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'esformatter-quote-props' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'esformatter-quote-props/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'esformatter-quote-props/index' {
  declare module.exports: $Exports<'esformatter-quote-props'>;
}
declare module 'esformatter-quote-props/index.js' {
  declare module.exports: $Exports<'esformatter-quote-props'>;
}
declare module 'esformatter-quote-props/test.js' {
  declare module.exports: $Exports<'esformatter-quote-props/test'>;
}
