// flow-typed signature: 5afa18177a74a3f291fd2d65c321776e
// flow-typed version: <<STUB>>/esformatter-jquery-chain_v^1.1.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'esformatter-jquery-chain'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'esformatter-jquery-chain' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'esformatter-jquery-chain/expected' {
  declare module.exports: any;
}

declare module 'esformatter-jquery-chain/plugin' {
  declare module.exports: any;
}

declare module 'esformatter-jquery-chain/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'esformatter-jquery-chain/expected.js' {
  declare module.exports: $Exports<'esformatter-jquery-chain/expected'>;
}
declare module 'esformatter-jquery-chain/plugin.js' {
  declare module.exports: $Exports<'esformatter-jquery-chain/plugin'>;
}
declare module 'esformatter-jquery-chain/test.js' {
  declare module.exports: $Exports<'esformatter-jquery-chain/test'>;
}
