// flow-typed signature: 297140f80ed88ce6833a459c7da2fc84
// flow-typed version: <<STUB>>/esformatter-literal-notation_v^1.0.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'esformatter-literal-notation'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'esformatter-literal-notation' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'esformatter-literal-notation/index' {
  declare module.exports: $Exports<'esformatter-literal-notation'>;
}
declare module 'esformatter-literal-notation/index.js' {
  declare module.exports: $Exports<'esformatter-literal-notation'>;
}
