// flow-typed signature: 27b277a4d68c140b78301c67b41bde97
// flow-typed version: <<STUB>>/express-partials_v^0.3.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'express-partials'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'express-partials' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'express-partials/test/fixtures/basic/app' {
  declare module.exports: any;
}

declare module 'express-partials/test/fixtures/chained-views/app' {
  declare module.exports: any;
}

declare module 'express-partials/test/fixtures/chained-views/index' {
  declare module.exports: any;
}

declare module 'express-partials/test/fixtures/default-layout/app' {
  declare module.exports: any;
}

declare module 'express-partials/test/fixtures/default-layout/index' {
  declare module.exports: any;
}

declare module 'express-partials/test/fixtures/locals/app' {
  declare module.exports: any;
}

declare module 'express-partials/test/fixtures/register/app' {
  declare module.exports: any;
}

declare module 'express-partials/test/fixtures/subdir/app' {
  declare module.exports: any;
}

declare module 'express-partials/test/test.partials.basic' {
  declare module.exports: any;
}

declare module 'express-partials/test/test.partials.chained-views' {
  declare module.exports: any;
}

declare module 'express-partials/test/test.partials.default-layout' {
  declare module.exports: any;
}

declare module 'express-partials/test/test.partials.haml-locals' {
  declare module.exports: any;
}

declare module 'express-partials/test/test.partials.register' {
  declare module.exports: any;
}

declare module 'express-partials/test/test.partials.subdir' {
  declare module.exports: any;
}

// Filename aliases
declare module 'express-partials/index' {
  declare module.exports: $Exports<'express-partials'>;
}
declare module 'express-partials/index.js' {
  declare module.exports: $Exports<'express-partials'>;
}
declare module 'express-partials/test/fixtures/basic/app.js' {
  declare module.exports: $Exports<'express-partials/test/fixtures/basic/app'>;
}
declare module 'express-partials/test/fixtures/chained-views/app.js' {
  declare module.exports: $Exports<'express-partials/test/fixtures/chained-views/app'>;
}
declare module 'express-partials/test/fixtures/chained-views/index.js' {
  declare module.exports: $Exports<'express-partials/test/fixtures/chained-views/index'>;
}
declare module 'express-partials/test/fixtures/default-layout/app.js' {
  declare module.exports: $Exports<'express-partials/test/fixtures/default-layout/app'>;
}
declare module 'express-partials/test/fixtures/default-layout/index.js' {
  declare module.exports: $Exports<'express-partials/test/fixtures/default-layout/index'>;
}
declare module 'express-partials/test/fixtures/locals/app.js' {
  declare module.exports: $Exports<'express-partials/test/fixtures/locals/app'>;
}
declare module 'express-partials/test/fixtures/register/app.js' {
  declare module.exports: $Exports<'express-partials/test/fixtures/register/app'>;
}
declare module 'express-partials/test/fixtures/subdir/app.js' {
  declare module.exports: $Exports<'express-partials/test/fixtures/subdir/app'>;
}
declare module 'express-partials/test/test.partials.basic.js' {
  declare module.exports: $Exports<'express-partials/test/test.partials.basic'>;
}
declare module 'express-partials/test/test.partials.chained-views.js' {
  declare module.exports: $Exports<'express-partials/test/test.partials.chained-views'>;
}
declare module 'express-partials/test/test.partials.default-layout.js' {
  declare module.exports: $Exports<'express-partials/test/test.partials.default-layout'>;
}
declare module 'express-partials/test/test.partials.haml-locals.js' {
  declare module.exports: $Exports<'express-partials/test/test.partials.haml-locals'>;
}
declare module 'express-partials/test/test.partials.register.js' {
  declare module.exports: $Exports<'express-partials/test/test.partials.register'>;
}
declare module 'express-partials/test/test.partials.subdir.js' {
  declare module.exports: $Exports<'express-partials/test/test.partials.subdir'>;
}
