// flow-typed signature: 1dbc8b40f08dc543883145515543181c
// flow-typed version: <<STUB>>/gulp-conventional-changelog_v^1.1.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-conventional-changelog'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-conventional-changelog' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'gulp-conventional-changelog/index' {
  declare module.exports: $Exports<'gulp-conventional-changelog'>;
}
declare module 'gulp-conventional-changelog/index.js' {
  declare module.exports: $Exports<'gulp-conventional-changelog'>;
}
