// flow-typed signature: 3ff576b63e9edc0bdeb28ec17009c6ee
// flow-typed version: <<STUB>>/gulp-jsdoc3_v^1.0.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-jsdoc3'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-jsdoc3' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gulp-jsdoc3/dist/gulp-jsdoc' {
  declare module.exports: any;
}

declare module 'gulp-jsdoc3/docs/gen/scripts/docstrap.lib' {
  declare module.exports: any;
}

declare module 'gulp-jsdoc3/docs/gen/scripts/fulltext-search-ui' {
  declare module.exports: any;
}

declare module 'gulp-jsdoc3/docs/gen/scripts/fulltext-search' {
  declare module.exports: any;
}

declare module 'gulp-jsdoc3/docs/gen/scripts/lunr.min' {
  declare module.exports: any;
}

declare module 'gulp-jsdoc3/docs/gen/scripts/prettify/jquery.min' {
  declare module.exports: any;
}

declare module 'gulp-jsdoc3/docs/gen/scripts/prettify/lang-css' {
  declare module.exports: any;
}

declare module 'gulp-jsdoc3/docs/gen/scripts/prettify/prettify' {
  declare module.exports: any;
}

declare module 'gulp-jsdoc3/docs/gen/scripts/sunlight' {
  declare module.exports: any;
}

declare module 'gulp-jsdoc3/docs/gen/scripts/toc' {
  declare module.exports: any;
}

declare module 'gulp-jsdoc3/src/gulp-jsdoc' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gulp-jsdoc3/dist/gulp-jsdoc.js' {
  declare module.exports: $Exports<'gulp-jsdoc3/dist/gulp-jsdoc'>;
}
declare module 'gulp-jsdoc3/docs/gen/scripts/docstrap.lib.js' {
  declare module.exports: $Exports<'gulp-jsdoc3/docs/gen/scripts/docstrap.lib'>;
}
declare module 'gulp-jsdoc3/docs/gen/scripts/fulltext-search-ui.js' {
  declare module.exports: $Exports<'gulp-jsdoc3/docs/gen/scripts/fulltext-search-ui'>;
}
declare module 'gulp-jsdoc3/docs/gen/scripts/fulltext-search.js' {
  declare module.exports: $Exports<'gulp-jsdoc3/docs/gen/scripts/fulltext-search'>;
}
declare module 'gulp-jsdoc3/docs/gen/scripts/lunr.min.js' {
  declare module.exports: $Exports<'gulp-jsdoc3/docs/gen/scripts/lunr.min'>;
}
declare module 'gulp-jsdoc3/docs/gen/scripts/prettify/jquery.min.js' {
  declare module.exports: $Exports<'gulp-jsdoc3/docs/gen/scripts/prettify/jquery.min'>;
}
declare module 'gulp-jsdoc3/docs/gen/scripts/prettify/lang-css.js' {
  declare module.exports: $Exports<'gulp-jsdoc3/docs/gen/scripts/prettify/lang-css'>;
}
declare module 'gulp-jsdoc3/docs/gen/scripts/prettify/prettify.js' {
  declare module.exports: $Exports<'gulp-jsdoc3/docs/gen/scripts/prettify/prettify'>;
}
declare module 'gulp-jsdoc3/docs/gen/scripts/sunlight.js' {
  declare module.exports: $Exports<'gulp-jsdoc3/docs/gen/scripts/sunlight'>;
}
declare module 'gulp-jsdoc3/docs/gen/scripts/toc.js' {
  declare module.exports: $Exports<'gulp-jsdoc3/docs/gen/scripts/toc'>;
}
declare module 'gulp-jsdoc3/index' {
  declare module.exports: $Exports<'gulp-jsdoc3'>;
}
declare module 'gulp-jsdoc3/index.js' {
  declare module.exports: $Exports<'gulp-jsdoc3'>;
}
declare module 'gulp-jsdoc3/src/gulp-jsdoc.js' {
  declare module.exports: $Exports<'gulp-jsdoc3/src/gulp-jsdoc'>;
}
